-- AlterTable
ALTER TABLE "Product" ADD COLUMN     "cost" DOUBLE PRECISION,
ALTER COLUMN "price" DROP NOT NULL;

-- AlterTable
ALTER TABLE "PurchaseItem" ADD COLUMN     "quantity" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "totalCost" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "unitCost" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "StockMovement" ADD COLUMN     "relatedIt" TEXT;
